/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marice
 */
public class menuusuario extends javax.swing.JFrame {

    /**
     * Creates new form menuusuario
     */
    public menuusuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtVenId = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        txtVenNombre = new javax.swing.JTextField();
        btnsalir = new javax.swing.JButton();
        limpiarCampos = new javax.swing.JButton();
        txtEmCodigo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtVenTelefono = new javax.swing.JTextField();
        txtVenDireccion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtVenCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtVenComisiones = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaV = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnsalir.setBackground(new java.awt.Color(204, 0, 0));
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        limpiarCampos.setText("Limpiar");
        limpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarCamposActionPerformed(evt);
            }
        });

        txtEmCodigo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID de usuario");

        jLabel2.setText("Codigo de de la facultad");

        jLabel3.setText("Nombre del Vendedor");

        btnGuardar.setText("Guardar Usuario");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefono");

        TablaV.setForeground(new java.awt.Color(0, 102, 255));
        TablaV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Vendedores", "Codigo del empleado", "Nombre ", "Telefono", "Direccion", "Correo", "Comisiones"
            }
        ));
        TablaV.setGridColor(new java.awt.Color(102, 204, 255));
        TablaV.setSelectionBackground(new java.awt.Color(204, 204, 204));
        TablaV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaV);

        jLabel5.setText("Direccion");

        jLabel6.setText("Correo");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Usuarios");

        jLabel7.setText("estado de la carrera");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtVenNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnModificar)
                        .addComponent(jButton1)))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel1)
                                        .addGap(40, 40, 40)
                                        .addComponent(txtVenId, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVenCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(5, 5, 5)
                                        .addComponent(txtVenDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(61, 61, 61)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVenComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(650, 650, 650)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnsalir)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVenId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEmCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtVenNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtVenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtVenComisiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtVenDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtVenCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limpiarCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        // 1. Obtener el modelo de tu tabla
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TablaV.getModel();

        // 2. Saber qué fila tiene seleccionada el usuario
        int filaSeleccionada = TablaV.getSelectedRow();

        // 3. Verificar si realmente seleccionó una fila
        if (filaSeleccionada >= 0) {
            modelo.removeRow(filaSeleccionada);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila de la tabla para eliminar.");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        int respuesta_cs = JOptionPane.showConfirmDialog(this,"¿Desea Cerrar Sesión?", "Cerrar Sesión",JOptionPane.YES_NO_OPTION);
        if (respuesta_cs == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void limpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarCamposActionPerformed

        txtVenId.setText("");
        txtEmCodigo.setSelectedIndex(0);
        txtVenNombre.setText("");
        txtVenTelefono.setText("");
        txtVenDireccion.setText("");
        txtVenCorreo.setText("");
        txtVenComisiones.setText("");

        // TODO add your handling code here:
        }

        // =========================================================================
        // NUEVOS MÉTODOS PARA CONECTAR A LA BASE DE DATOS
        // =========================================================================

        public void llenarComboBoxBaseDatos() {
            txtEmCodigo.removeAllItems();
            txtEmCodigo.addItem("Seleccione un código");

            // Datos de conexión (Ajusta la URL, usuario y contraseña según tu entorno)
            String url = "jdbc:mysql://localhost:3306/tu_base_de_datos";
            String usuario = "root";
            String password = "123456";
            String sql = "SELECT codigo_empleado FROM empleados";

            try (java.sql.Connection con = java.sql.DriverManager.getConnection(url, usuario, password);
                java.sql.PreparedStatement ps = con.prepareStatement(sql);
                java.sql.ResultSet rs = ps.executeQuery()) {

                while (rs.next()) {
                    txtEmCodigo.addItem(rs.getString("codigo_empleado"));
                }

            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar códigos de empleados: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

        public void actualizarTablaBaseDatos() {
            DefaultTableModel modelo = (DefaultTableModel) TablaV.getModel();
            modelo.setRowCount(0);

            String url = "jdbc:mysql://localhost:3306/tu_base_de_datos";
            String usuario = "root";
            String password = "123456";
            String sql = "SELECT * FROM vendedores";

            try (java.sql.Connection con = java.sql.DriverManager.getConnection(url, usuario, password);
                java.sql.PreparedStatement ps = con.prepareStatement(sql);
                java.sql.ResultSet rs = ps.executeQuery()) {

                while (rs.next()) {
                    Object[] fila = {
                        rs.getString("id_vendedor"),       // Cambia por el nombre de tu columna ID
                        rs.getString("codigo_empleado"),   // Cambia por tu columna Código
                        rs.getString("nombre_vendedor"),   // Cambia por tu columna Nombre
                        rs.getString("telefono"),          // Cambia por tu columna Teléfono
                        rs.getString("direccion"),         // Cambia por tu columna Dirección
                        rs.getString("correo"),            // Cambia por tu columna Correo
                        rs.getString("comisiones")         // Cambia por tu columna Comisiones
                    };
                    modelo.addRow(fila);
                }

            } catch (java.sql.SQLException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar la tabla de vendedores: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }

            // TODO add your handling code here:
    }//GEN-LAST:event_limpiarCamposActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        abrirArchivoSistema("ayudaComisionReporte.chm");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        // 1. Obtener el modelo de tu tabla
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel)  TablaV.getModel();

        // 2. Crear la fila con los datos de los JTextFields
        Object[] nuevaFila = {
            txtVenId.getText(),
            txtEmCodigo.getSelectedItem().toString(),
            txtVenNombre.getText(),
            txtVenTelefono.getText(),
            txtVenDireccion.getText(),
            txtVenCorreo.getText(),
            txtVenComisiones.getText()
        };

        // 3. Añadir la fila a la tabla
        modelo.addRow(nuevaFila);

        // 4. Limpiar los campos de texto para el siguiente registro
        txtVenId.setText("");
        txtEmCodigo.setSelectedIndex(0);
        txtVenNombre.setText("");
        txtVenTelefono.setText("");
        txtVenDireccion.setText("");
        txtVenCorreo.setText("");
        txtVenComisiones.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void TablaVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaVMouseClicked

        int filaSeleccionada = TablaV.getSelectedRow();
        if (filaSeleccionada >= 0) {
            txtVenId.setText(TablaV.getValueAt(filaSeleccionada, 0).toString());
            txtEmCodigo.setSelectedItem(TablaV.getValueAt(filaSeleccionada, 1).toString());
            txtVenNombre.setText(TablaV.getValueAt(filaSeleccionada, 2).toString());
            txtVenTelefono.setText(TablaV.getValueAt(filaSeleccionada, 3).toString());
            txtVenDireccion.setText(TablaV.getValueAt(filaSeleccionada, 4).toString());
            txtVenCorreo.setText(TablaV.getValueAt(filaSeleccionada, 5).toString());
            txtVenComisiones.setText(TablaV.getValueAt(filaSeleccionada, 6).toString());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_TablaVMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        // 1. Obtener el modelo de tu tabla
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TablaV.getModel();

        // 2. Saber qué fila tiene seleccionada el usuario
        int filaSeleccionada = TablaV.getSelectedRow();

        // 3. Verificar si seleccionó una fila antes de intentar modificar
        if (filaSeleccionada >= 0) {

            // 4. Actualizar cada columna de la fila seleccionada con el texto actual de los campos
            modelo.setValueAt(txtVenId.getText(), filaSeleccionada, 0);         // Columna 0: ID
            modelo.setValueAt(txtEmCodigo.getSelectedItem().toString(), filaSeleccionada, 1);     // Columna 1: Código
            modelo.setValueAt(txtVenNombre.getText(), filaSeleccionada, 2);     // Columna 2: Nombre
            modelo.setValueAt(txtVenTelefono.getText(), filaSeleccionada, 3);   // Columna 3: Teléfono
            modelo.setValueAt(txtVenDireccion.getText(), filaSeleccionada, 4);  // Columna 4: Dirección
            modelo.setValueAt(txtVenCorreo.getText(), filaSeleccionada, 5);     // Columna 5: Correo
            modelo.setValueAt(txtVenComisiones.getText(), filaSeleccionada, 6); // Columna 6: Comisiones

            // 5. Limpiar los campos de texto tras la modificación (Opcional)
            txtVenId.setText("");
            txtEmCodigo.setSelectedIndex(0);
            txtVenNombre.setText("");
            txtVenTelefono.setText("");
            txtVenDireccion.setText("");
            txtVenCorreo.setText("");
            txtVenComisiones.setText("");

        } else {
            // Alerta si el usuario no hizo clic en ninguna fila de la tabla
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona primero una fila de la tabla para poder modificarla.");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuusuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaV;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarCampos;
    private javax.swing.JComboBox<String> txtEmCodigo;
    private javax.swing.JTextField txtVenComisiones;
    private javax.swing.JTextField txtVenCorreo;
    private javax.swing.JTextField txtVenDireccion;
    private javax.swing.JTextField txtVenId;
    private javax.swing.JTextField txtVenNombre;
    private javax.swing.JTextField txtVenTelefono;
    // End of variables declaration//GEN-END:variables

    private void abrirArchivoSistema(String ayudaComisionReportechm) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

  
}
